name: Set manifest version from tag

on:
  push:
    tags:
      - '*'

jobs:
  update-manifest-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set manifest version from git tag
        run: |
          TAG=${GITHUB_REF##*/}
          jq ".version = \"${TAG}\"" custom_components/fast_fan/manifest.json > tmp && mv tmp custom_components/fast_fan/manifest.json

      - name: Commit and push updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add custom_components/fast_fan/manifest.json
          git commit -m "Set manifest version to ${TAG}" || echo "No changes to commit"
          git push
